name: Pycodestyle Code Check

on:
  push:
    branches: 
      - '**'  

jobs:
  pycodestyle-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Install pycodestyle
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      - name: Run pycodestyle
        run: pycodestyle --exclude=venv .
